#!/usr/bin/env bash

domain=$1

if [ "$#" -eq 2 ]; then
    subdomain=$2
else
    subdomain=("www" "lb-01" "web-01" "web-02")
fi

for sub in "${subdomain[@]}"; do
    echo -n "The subdomain $sub"
    dig +short "$sub.$domain" | awk '{ print " points to " $1}'
done
