#!/usr/bin/env bash

# Install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Create a certificate using certbot
sudo certbot certonly --standalone -d www.example.com

# Configure HAProxy
sudo bash -c 'cat <<EOF > /etc/haproxy/haproxy.cfg
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend www-https
    bind *:443 ssl crt /etc/letsencrypt/live/www.example.com/fullchain.pem
    http-request redirect scheme https unless { ssl_fc }
    default_backend servers

backend servers
    balance roundrobin
    server web1 192.168.0.1:80 check

EOF'

# Restart HAProxy
sudo service haproxy restart
