#!/usr/bin/env bash
# This script configures Nginx to have a custom 404 page

# Install Nginx if it's not already installed
apt-get update
apt-get install -y nginx

# Create a custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configure Nginx to use the custom 404 page
sed -i '48i \\\terror_page 404 /404.html;' /etc/nginx/sites-available/default

# Enable the new configuration
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

# Restart Nginx
service nginx restart
