#!/usr/bin/env bash
# This script configures Nginx to add a custom HTTP header

# Install Nginx if it's not already installed
sudo apt-get update
sudo apt-get install -y nginx

# Get the hostname of the machine
HOSTNAME=$(hostname)

# Configure Nginx to add a custom header "X-Served-By" with the value of the hostname
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    location / {
        add_header X-Served-By $HOSTNAME;
    }
}" | sudo tee /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo systemctl restart nginx
