#!/usr/bin/env bash
# This script configures a new Ubuntu machine to be identical to web-01 and adds a custom Nginx header
sudo apt-get -y update
sudo apt-get -y install nginx
HOSTNAME=$(hostname)
sudo sed -i "37i \tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
sudo service nginx restart
