#!/usr/bin/env bash
# This script configures HAProxy to distribute requests to two web servers

# Install HAProxy if it's not already installed
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy
echo "
frontend http_front
   bind *:80
   stats uri /haproxy?stats
   default_backend http_back

backend http_back
   balance roundrobin
   server web01 [54.164.145.199]-web-01:80 check
   server web02 [34.229.67.107]-web-02:80 check
" | sudo tee /etc/haproxy/haproxy.cfg

# Restart HAProxy to apply the changes
sudo systemctl restart haproxy
