#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

# Initializing the counter
counter=0

# Using an until loop to display "Best School" 10 times
until [ $counter -ge 10 ]; do
    echo "Best School"
    ((counter++))
done
