#!/usr/bin/env bash
# This script displays "Best School" 10 times, with a special case for the 9th iteration

# Initializing the counter
counter=0

# Using a while loop to display "Best School" 10 times
while [ $counter -lt 10 ]; do
    # Using an if statement to check for the 9th iteration
    if [ $counter -eq 8 ]; then
        echo -e "Best School\nHi"
    else
        echo "Best School"
    fi

    # Incrementing the counter
    ((counter++))
done
