#!/usr/bin/env bash
# This script displays numbers and corresponding messages using a case statement

# Initializing the counter
counter=1

# Using a while loop to iterate from 1 to 20
while [ $counter -le 20 ]; do
    # Using a case statement to display different messages for specific iterations
    case $counter in
        4)
            echo "4 and then bad luck from China"
            ;;
        9)
            echo "9 and then bad luck from Japan"
            ;;
        17)
            echo "17 and then bad luck from Italy"
            ;;
        *)
            echo $counter
            ;;
    esac

    # Incrementing the counter
    ((counter++))
done
