#!/usr/bin/env bash
# Bash script that provides information about the school file

FILE="school"

# Check if the file exists
if [ -e "$FILE" ]; then
    echo "school file exists"
    
    # Check if the file is empty
    if [ -s "$FILE" ]; then
        echo "school file is not empty"
        
        # Check if the file is a regular file
        if [ -f "$FILE" ]; then
            echo "school is a regular file"
        fi
    else
        echo "school file is empty"
    fi
else
    echo "school file does not exist"
fi
